routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/home', function () {
//     return view('home');
// });

Auth::routes();

// ruta de funcion ajax para obtener las areas
Route::get('getareas','Area\AreaController@getAreas');
Route::get('getcontratos','Precargas\TipoContratoController@getContratos');
Route::get('getpuestos','Puesto\PuestoController@getPuestos');
Route::get('getSucursal','Sucursal\SucursalController@getSucursal');
Route::get('getbancos','Banco\BancoController@getBancos');

Route::resource('giros','Giro\GiroController', ['except'=>'show']);
Route::resource('formacontactos','FormaContacto\FormaContactoController');

Route::resource('clientes','Personal\PersonalController');
Route::resource('clientes.direccionfisica','Personal\PersonalDireccionFisicaController');
Route::resource('clientes.contacto','Personal\PersonalContactoController');
Route::resource('clientes.datosgenerales','Personal\PersonalDatosGeneralesController', ['except'=>'show']);

Route::resource('clientes.crm','Personal\PersonalCRMController');
//---------------------------------------------------------------------
Route::resource('familias','Precargas\FamiliaController', ['except'=>'show']);
Route::resource('tipos','Precargas\TipoController', ['except'=>'show']);
Route::resource('subtipos','Precargas\SubtipoController', ['except'=>'show']);
Route::resource('unidad','Precargas\UnidadController', ['except'=>'show']);
Route::resource('presentaciones','Precargas\PresentacionController', ['except'=>'show']);
Route::resource('calidad','Precargas\CalidadController', ['except'=>'show']);
Route::resource('acabados','Precargas\AcabadoController', ['except'=>'show']);
Route::resource('marcas','Precargas\MarcaController', ['except'=>'show']);
//---------------------------------------------------------------------------
Route::get('buscarcotizacion','Cotizacion\CotizacionController@buscarCotizacion');
Route::get('buscarcliente','Personal\PersonalController@buscar');

Route::resource('productos','Producto\ProductoController');


Route::get('cotizaciones/buscarproductos','Cotizacion\CotizacionController@buscarproductos');
// Route::resource('incotizacion','Cotizacion\InCotizacionController');
Route::get('incotizacion/{cotizacion}','Cotizacion\InCotizacionController@index');
Route::post('incotizacion','Cotizacion\InCotizacionController@store');
Route::post('eliminarproductoencotizacion/{inCotizacion}','Cotizacion\InCotizacionController@destroy');
Route::resource('cotizaciones','Cotizacion\CotizacionController');
Route::post('cotizaciones/cotizacionautosave','Cotizacion\CotizacionController@autosave');
Route::get('buscarproducto','Producto\ProductoController@buscar');
Route::get('buscarempleado','Empleado\EmpleadoController@buscar');
Route::get('buscarprovedor','Provedor\ProvedorController@buscar');
Route::get('buscargiro','Giro\GiroController@buscar');
Route::get('buscarformacontacto','FormaContacto\FormaContactoController@buscar');
Route::get('buscarmarca','Precargas\MarcaController@buscar');
Route::get('buscaracabado','Precargas\AcabadoController@buscar');
Route::get('buscarcalidad','Precargas\CalidadController@buscar');
Route::get('buscarfamilia','Precargas\FamiliaController@buscar');
Route::get('buscarpresentacion','Precargas\PresentacionController@buscar');
Route::get('buscarsubtipo','Precargas\SubtipoController@buscar');
Route::get('buscartipo','Precargas\TipoController@buscar');
Route::get('buscarunidad','Precargas\UnidadController@buscar');
// Route::resource('pruebas','PruebasController', ['except'=>'show']);
//-----------------------------------------------------
Route::resource('provedores','Provedor\ProvedorController');
Route::get('buscarprovedor','Provedor\ProvedorController@buscar');
Route::resource('provedores.direccionfisica','Provedor\ProvedorDireccionFisicaController');
Route::resource('provedores.datosgenerales','Provedor\ProvedorDatosGeneralesController', ['except'=>'show']);
Route::resource('provedores.contacto','Provedor\ProvedorContactoController');
Route::resource('provedores.crm','Provedor\ProvedorCRMController');
//----------------------------------------------------------
Route::get('prueba','Provedor\ProvedorDireccionFisicaController@prueba');

// Route::get('busqueda','Personal\PersonalController@busqueda');
Route::resource('empleados','Empleado\EmpleadoController');
Route::resource('empleados.datoslaborales','Empleado\EmpleadosDatosLabController');
Route::resource('empleados.estudios','Empleado\EmpleadosEstudiosController');
Route::resource('empleados.emergencias','Empleado\EmpleadosEmergenciasController');
Route::resource('empleados.vacaciones','Empleado\EmpleadosVacacionesController');
Route::resource('empleados.faltas','Empleado\EmpleadosFaltasAdministrativasController');
Route::resource('contratos','Precargas\TipoContratoController');
Route::resource('bajas','Precargas\TipoBajaController');
//---------BLUE PRINTS---------------------------------
Route::get('sucursales',function(){

	return View::make('sucursales.sucursales');
});
Route::get('gastos',function(){

	return View::make('gastos.gastos');
});
Route::get('consulta',function(){

	return View::make('empleadoconsulta.consulta');
});
Route::get('bonos',function(){

	return View::make('Empleadobonos.bonos');
});
Route::get('comision',function(){

	return View::make('Empleadobonos.comision');
});
//---------------------------------------------------------------------------
Route::resource('areas','Area\AreaController', ['except'=>'show']);
Route::resource('puestos','Puesto\PuestoController', ['except'=>'show']);
Route::resource('bancos','Banco\BancoController', ['except'=>'show']);
//--------------------------------------------------------------------

resources/views/empleadodatoslab/index.blade.php
@extends('layouts.infoempleado')
@section('infoempleado')



	@if (count($datoslaborales) == 0)
			<h3>Aún no tienes historial laboral</h3>
		@endif
		@if (count($datoslaborales) !=0)
            {{$fecha=''}}
		     @foreach ($datoslaborales as $dato)
		     <?php $fecha=$dato->fechacontratacion ?>
		     @endforeach
			

			<div class="panel panel-primary">
      <div class="panel-heading" align="center"><strong>Historial Laboral</strong></div>
      <div class="panel-body" ><strong>Fecha de Contratación: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{$dato->fechacontratacion}}</strong>
        <div align="right">
      	<a class="btn btn-info btn-md" href="{{ route('empleados.datoslaborales.edit',['empleado'=>$empleado,'datoslaborale'=>$dato]) }}">
				<strong>Agregar</strong>
			</a></div>

      </div>
    </div><table class="table table-striped table-bordered table-hover" style="color:rgb(51,51,51); border-collapse: collapse; margin-bottom: 0px;">
				<thead>
					<tr class="info">
						<th>Área</th>
						<th>Puesto</th>
						<th>Salario Nominal</th>
						<th>Fecha de Actualización</th>
						<th>Lugar de Trabajo</th>


						<th>Operaciones</th>
					</tr>
				</thead>
                <tbody>
				@foreach ($datoslaborales as $dato)
					<tr class="active">
@if($areas==null)
<td>NO DEFINIDO</td>
@else
@foreach ($areas as $area)
								{{-- expr --}}

								 @if ($dato->area_id == $area->id)
								 <td>{{ $area->nombre }}</td>
									{{-- expr --}}

									
								@endif
							@endforeach
						@endif
@if($puestos==null)
<td>NO DEFINIDO</td>
@else
@foreach ($puestos as $puesto)
								{{-- expr --}}

								 @if ($dato->puesto_id == $puesto->id)
								 <td>{{ $puesto->nombre }}</td>
									{{-- expr --}}

									
								@endif
							@endforeach
						@endif



						<td>{{$dato->salarionom}}</td>
						<td>{{$dato->fechaactualizacion}}</td>
						<td>{{$dato->lugartrabajo}}</td>


						<td>

							<a class="btn btn-success btn-sm" href="{{ route('empleados.datoslaborales.show',['empleado'=>$empleado,'datoslaborale'=>$dato]) }}">
						<strong>Ver</strong>	</a>

							

					</tr>
						</td>


					</tbody>
				@endforeach
			</table>
		@endif



@endsection

resources/views/empleadodatoslab/view.blade.php
@extends('layouts.infoempleado')
@section('infoempleado')
	{{-- expr --}}
	
	
	
	
	<div>
		<ul class="nav nav-pills nav-justified">
			<li role="presentation" class=""><a href="{{ route('empleados.show',['empleado'=>$empleado]) }}"  class="ui-tabs-anchor">Generales:</a></li>

			<li role="presentation" class="active"><a href="{{ route('empleados.datoslaborales.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Laborales:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.estudios.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Estudios:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.emergencias.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Emergencias:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.vacaciones.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Vacaciones:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.faltas.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Administrativo:</a></li>
		</ul>
	</div>
	<div class="panel-default">

		<div class="panel-heading"><h5>Laborales:</h5>

		{{-- MODAL --}}
		 <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info " data-toggle="modal" data-target="#formularioTutor">Open Large Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="formularioTutor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="position: 0,0 !important; right: -200px;">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>This is a large modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

		{{-- MODAL --}}

		</div>
		<div class="panel-body">
			<div class="col-md-12 offset-md-2 mt-3"> 
				<div class="form-group col-xs-3">
					<label class="control-label" for="fechacontratacion">Fecha de contratación:</label>
					
					<dd>{{ $datoslab->fechacontratacion }}</dd>
				</div>



				<div class="form-group col-xs-3">
					<label class="control-label" for="contrato">Tipo de contrato:</label>
					<dd>{{ $contrato }}</dd>
				</div>




                <div class="form-group col-xs-3">
					<label class="control-label" for="area">Área:</label>
					
					<dd>{{ $area }}</dd>
				</div>
				
				<div class="form-group col-xs-3">
					<label class="control-label" for="puesto">Puesto:</label>
					<dd>{{ $puesto }}</dd>
				</div>
				



			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="salarionom">Salario Nóminal:</label>
					<dd>{{ $datoslab->salarionom }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="salariodia">Salario Diario:</label>
					<dd>{{ $datoslab->salariodia }}</dd>
				</div>

				

				<div class="form-group col-xs-3">
					<label class="control-label" for="periodopaga">Periodicidad de Pago:</label>
					<dd>{{ $datoslab->periodopaga }}</dd>
				</div>
			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="prestaciones">Prestaciones:</label>
					<dd>{{ $datoslab->prestaciones }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="regimen">Régimen de Contratación:</label>
					<dd>{{ $datoslab->regimen }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="hentrada">Hora de Entrada:</label>
					<dd>{{ $datoslab->hentrada }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="hsalida">Hora de Salida:</label>
					<dd>{{ $datoslab->hsalida }}</dd>
				</div>
			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="hcomida">Tiempo de Comida:</label>
					<dd>{{ $datoslab->hcomida }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="lugartrabajo">Lugar de Trabajo:</label>
					<dd>{{ $datoslab->lugartrabajo }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="banco">Banco:</label>
					<dd>{{ $datoslab->banco }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="cuenta">Cuenta:</label>
					<dd>{{ $datoslab->cuenta }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="clabe">CLABE:</label>
					<dd>{{ $datoslab->clabe }}</dd>
				</div>
			</div>
			<a class="btn btn-info btn-md" href="{{ route('empleados.datoslaborales.edit',['empleado'=>$empleado,'datoslaborale'=>$datoslab]) }}">
				<strong>Editar</strong>
			</a>
		</div>
	</div>
@endsection